In [2]:
arr = [1, 2, 3]
print(arr * 5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [7]:
import numpy as np
ar = [1, 2, 3]
ar1 = np.array(ar)
ar1 = ar1*5
print(ar1)
print(type(ar1))

#2d
arr = [[1, 2, 3],
       [4, 5, 6]]
ar2 = np.array(arr)

#3d

ar3 = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[1, 2, 3],
     [4, 5, 6]],
    [[1, 2, 3],
     [4, 5, 6]]
    ])

[ 5 10 15]
<class 'numpy.ndarray'>


In [15]:
#dimension
print(ar1.ndim)
print(ar2.ndim)
print(ar3.ndim)

#shape
print(ar1.shape)
print(ar2.shape)
print(ar3.shape)

#data type
print(ar1.dtype)
print(ar2.dtype)
print(ar3.dtype)

#size
print(ar1.size)
print(ar2.size)
print(ar3.size)

1
2
3
(3,)
(2, 3)
(3, 2, 3)
int64
int64
int64
3
6
18


In [17]:
arr = np.array([1, 2, 4.4, 'joy'])
print(arr.dtype)

<U32


In [2]:
import numpy as np
lst = [10, True, 'hi', 10.5]
arr = np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

['10' 'True' 'hi' '10.5']
<class 'numpy.ndarray'>
<U32


In [13]:

# arr = np.zeros((2, 3), dtype=np.int8)
# arr = np.zeros_like(ar3)
arr = np.ones((3, 4, 3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
float64
(3, 4, 3)
3
36


In [9]:
lst = [10, 20, 30, 40, 50]

arr = np.array(lst)
arr = arr*1.8 + 32
print(arr)


[ 50.  68.  86. 104. 122.]


In [12]:
lap = [100, 200, 340, 360, 450]
arr = np.array(lap)
print(arr.dtype)
print(arr.shape)
print(arr.size)

arr = arr/60
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)


int64
(5,)
5
[1.67 3.33 5.67 6.   7.5 ]
float64
(5,)
5
