In [49]:
import numpy as np

arr = np.random.randint(1, 100, size=(10, 5))
arr.shape
b = arr.reshape(5, 10)
b.shape
b.ndim
b.size
b

array([[91, 41, 79, 17, 18, 98, 23, 37, 56, 45],
       [54, 80, 41, 55, 81, 11, 14, 28, 11, 82],
       [67, 51, 84, 99, 74,  2, 63, 15, 96, 64],
       [61, 80, 67, 55, 10, 28, 62, 47, 82, 50],
       [20, 32, 34, 30, 13,  3, 20, 67, 75, 24]])

In [17]:
flat = b.flatten()
print(flat.ndim)

col_wise_flat = np.ravel(b, order='F')
print(col_wise_flat)

1
[18 41 94 88 78 51 86 53 92 95 94 13 40 68 71 33  1 41 66 54 43 96 28 14
 26 87 62 15 14 42 70 80 95 46  3 79  2 86 89 85 14 81 21 61 73 67 21 76
 53 62]


In [18]:
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

print(a)
print(b)

[[4 3 9]
 [5 7 8]]
[[20 25 24]
 [23 24 27]]


In [20]:
con_row = np.concatenate((a, b), axis=0)

print(con_row)

con_col = np.concatenate((a,b), axis=1)
print(con_col)

[[ 4  3  9]
 [ 5  7  8]
 [20 25 24]
 [23 24 27]]
[[ 4  3  9 20 25 24]
 [ 5  7  8 23 24 27]]


In [21]:
mat = np.array([[10, 20, 30],
                [40, 50, 60]])
tran = mat.T
print(tran)

[[10 40]
 [20 50]
 [30 60]]


In [25]:
a = np.random.randint(1, 10, size=(10,))

print(a)
sa = np.array_split(a, 3)
print(sa)


[5 2 2 2 1 2 5 9 5 3]
[array([5, 2, 2, 2]), array([1, 2, 5]), array([9, 5, 3])]


In [41]:
x = np.array([10, 20, 30, 100])
y = np.array([2, 3, 4, 5])

add = x+2
print(add)

sin_val = np.sin(x)
print(sin_val)

deg_con = np.rad2deg(x)
print(deg_con)

base_10 = np.log10(x)
print(base_10)

sqrt = np.sqrt(x)
print(sqrt)

s = np.sum(x)
print(s)

cusum = np.cumsum(x)
print(cusum)

sq = np.square(y)
print(sq)

[ 12  22  32 102]
[-0.54402111  0.91294525 -0.98803162 -0.50636564]
[ 572.95779513 1145.91559026 1718.87338539 5729.57795131]
[1.         1.30103    1.47712125 2.        ]
[ 3.16227766  4.47213595  5.47722558 10.        ]
160
[ 10  30  60 160]
[ 4  9 16 25]


In [ ]:
x = np.array([[30, 10, 20],
              [50, 60, 40]])

hs = np.sort(x, axis=1)
print(hs)

vs = np.sort(x, axis=0)
print(vs)

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])

if a.size != b.size:
  print(-1)

-1
